/*
 Navicat Premium Data Transfer

 Source Server         : random
 Source Server Type    : MySQL
 Source Server Version : 80033 (8.0.33)
 Source Host           : localhost:3306
 Source Schema         : cucer1

 Target Server Type    : MySQL
 Target Server Version : 80033 (8.0.33)
 File Encoding         : 65001

 Date: 21/07/2023 15:47:52
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for db
-- ----------------------------
DROP TABLE IF EXISTS `db`;
CREATE TABLE `db` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `author` varchar(255) DEFAULT NULL,
  `picture` varchar(255) DEFAULT NULL,
  `time` varchar(255) DEFAULT NULL,
  `version` varchar(255) DEFAULT NULL,
  `score` varchar(255) DEFAULT NULL,
  `count_people` int DEFAULT NULL COMMENT '评价人数',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=230 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----------------------------
-- Records of db
-- ----------------------------
BEGIN;
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (1, '如何屠龙：中世纪英雄冒险指南', '[美]凯特琳·史蒂文森 ', 'https://img9.doubanio.com/view/subject/s/public/s34544464.jpg', '2023-6', '精装', '8.0', 130);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (2, '伊塔洛·卡尔维诺：写小说的人，讲故事的人', '[法]让-保罗·曼加纳罗 ', 'https://img2.doubanio.com/view/subject/s/public/s34501512.jpg', '2023-6', '精装', '8.3', 61);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (3, '避孕简史', '[美]唐娜•J.德鲁克 ', 'https://img9.doubanio.com/view/subject/s/public/s34528385.jpg', '2023-6', '平装', '7.5', 36);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (4, '德罗西大街', '[美] 威尔·艾斯纳 ', 'https://img1.doubanio.com/view/subject/s/public/s34547789.jpg', '2023-7', '精装', '9.0', 54);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (5, '论国家：法兰西公学院课程（1989-1992）', '[法国] 皮埃尔·布迪厄 ', 'https://img2.doubanio.com/view/subject/s/public/s34504643.jpg', '2023-6', '精装', '8.2', 50);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (6, '克服欧洲', '[塞尔维亚] 佐兰·米卢蒂诺维奇 ', 'https://img9.doubanio.com/view/subject/s/public/s34575234.jpg', '2023-6', '平装', '没有评分​', 5);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (7, '酒之爵与人之爵：东周礼书所见酒器等级礼制初探', '阎步克 ', 'https://img9.doubanio.com/view/subject/s/public/s34507615.jpg', '2023-6', '精装', '9.2', 53);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (8, '鳄鱼', '莫言 ', 'https://img2.doubanio.com/view/subject/s/public/s34545983.jpg', '2023-6', '精装', '7.5', 948);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (9, '哲学的指引：斯多葛哲学的生活之道', '[意]马西莫·匹格里奇 ', 'https://img9.doubanio.com/view/subject/s/public/s34559766.jpg', '2023-6', '平装', '没有评分​', 7);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (10, '医生，你在想什么：每个人的疾病课', '王兴 ', 'https://img9.doubanio.com/view/subject/s/public/s34550176.jpg', '2023-6', '平装', '8.4', 122);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (11, '我还能看到多少次满月升起', '[日] 坂本龙一 ', 'https://img9.doubanio.com/view/subject/s/public/s34559136.jpg', '2023-6', '精装', '9.5', 361);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (12, '非地点：超现代性人类学导论', '[法]马克·奥热 ', 'https://img9.doubanio.com/view/subject/s/public/s34577835.jpg', '2023-6', '平装', '7.5', 29);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (13, '谁住进了养老院：当代中国的“银发海啸”与照护难题', '【美】葛玫 ', 'https://img2.doubanio.com/view/subject/s/public/s34553042.jpg', '2023-6', '平装', '7.4', 140);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (14, '残酷的乐观主义', '[美]劳伦·贝兰特 ', 'https://img9.doubanio.com/view/subject/s/public/s34583304.jpg', '2023-7', '平装', '没有评分​', 9);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (15, '大学，有什么用？：剑桥教授为大学教育一辩', '[英] 斯蒂芬·科利尼 ', 'https://img1.doubanio.com/view/subject/s/public/s34550889.jpg', '2023-6', '平装', '8.3', 71);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (16, '抵达：一部政治演化史', '包刚升 ', 'https://img2.doubanio.com/view/subject/s/public/s34559133.jpg', '2023-7', '平装', '8.4', 55);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (17, '科塔萨尔：我们共同的国度', '[乌拉圭]克里斯蒂娜·佩里·罗西 ', 'https://img2.doubanio.com/view/subject/s/public/s34539441.jpg', '2023-6', '精装', '7.8', 28);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (18, '接吻的中国史', '胡文辉 ', 'https://img2.doubanio.com/view/subject/s/public/s34523762.jpg', '2023-6', '平装', '7.8', 155);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (19, '小雷因寺', '张亦霆 ', 'https://img2.doubanio.com/view/subject/s/public/s34535821.jpg', '2023-6', '精装', '7.8', 66);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (20, '一张中国大书桌', '岱峻 ', 'https://img1.doubanio.com/view/subject/s/public/s34550179.jpg', '2023-6', '精装', '没有评分​', 9);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (21, '人类世的“资本论”', '[日]斋藤幸平 ', 'https://img9.doubanio.com/view/subject/s/public/s34543165.jpg', '2023-6', '平装', '8.5', 83);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (22, '实验室生活：科学事实的建构过程', '[法]布鲁诺·拉图尔 / [英]史蒂夫·伍尔加 ', 'https://img2.doubanio.com/view/subject/s/public/s34558083.jpg', '2023-6', '精装', '9.3', 32);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (23, '代价高昂的健康：美国卫生保健怎么了、怎么办？', '［美］马蒂·马卡里 ', 'https://img9.doubanio.com/view/subject/s/public/s34550615.jpg', '2023-6', '平装', '没有评分​', 3);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (24, '金钱心理学：财富、人性和幸福的永恒真相', '[美] 摩根 · 豪泽尔 / Morgan Housel ', 'https://img9.doubanio.com/view/subject/s/public/s34540496.jpg', '2023-6', '平装', '8.5', 480);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (25, '社会为什么对年轻人冷酷无情', '[日]山田昌弘 ', 'https://img1.doubanio.com/view/subject/s/public/s34545859.jpg', '2023-6', '平装', '8.3', 105);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (26, '能量，性，自杀：线粒体与生命的意义', '[英] 尼克·莱恩（Nick Lane） ', 'https://img1.doubanio.com/view/subject/s/public/s34543099.jpg', '2023-6', '平装', '8.3', 63);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (27, '中国绘画：五代至南宋', '[美]巫鸿 ', 'https://img9.doubanio.com/view/subject/s/public/s34541034.jpg', '2023-6', '精装', '9.7', 100);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (28, '春天及一切：威廉斯诗选', '[美]威廉·卡洛斯·威廉斯 ', 'https://img9.doubanio.com/view/subject/s/public/s34578164.jpg', '2023-7', '平装', '8.7', 33);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (29, '捕杀：保护猎艳者的谎言、监视与阴谋', '[美]罗南·法罗 ', 'https://img9.doubanio.com/view/subject/s/public/s34531564.jpg', '2023-6', '平装', '7.7', 73);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (30, '街角：一个内城社区的一年', '[美] 大卫·西蒙 / [美] 艾德华·伯恩斯 ', 'https://img9.doubanio.com/view/subject/s/public/s34562914.jpg', '2023-7', '平装', '没有评分​', 7);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (31, '德意志文学简史', '[德]海因茨·史腊斐 ', 'https://img9.doubanio.com/view/subject/s/public/s34584495.jpg', '2023-7', '平装', '没有评分​', 11);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (32, '龙与狮的对话：翻译与马戛尔尼访华使团', '王宏志 ', 'https://img1.doubanio.com/view/subject/s/public/s34524658.jpg', '2023-6', '精装', '9.6', 43);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (33, '清代广州旅本', '[美]嘉约翰 编著 ', 'https://img2.doubanio.com/view/subject/s/public/s34579533.jpg', '2023-7', '平装', '没有评分​', 6);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (34, '偶然的宇宙', '[美] 艾伦·莱特曼 ', 'https://img1.doubanio.com/view/subject/s/public/s34563760.jpg', '2023-7', '精装', '8.3', 15);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (35, '入山与出塞：李零考古艺术史文集', '李零 ', 'https://img2.doubanio.com/view/subject/s/public/s34505251.jpg', '2023-6', '精装', '8.5', 16);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (36, '拉丁美洲政治思想简史', '（阿）帕特里夏·富内斯 ', 'https://img2.doubanio.com/view/subject/s/public/s34563882.jpg', '2023-6', '平装', '没有评分​', 3);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (37, '夏：“季节四部曲”之四', '[英]阿莉·史密斯 ', 'https://img9.doubanio.com/view/subject/s/public/s34545644.jpg', '2023-6', '精装', '9.2', 47);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (38, '邻居', '[日] 雫井脩介 ', 'https://img1.doubanio.com/view/subject/s/public/s34528340.jpg', '2023-6', '平装', '7.7', 1307);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (39, '女性史：文艺复兴与启蒙时期卷', '[法]乔治·杜比 等主编 ', 'https://img1.doubanio.com/view/subject/s/public/s34533070.jpg', '2023-6', '精装', '没有评分​', 3);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (40, '女孩之书', '[挪威] 妮娜·布罗克曼 著 / [挪威] 艾伦·斯托肯·达尔 著 / [挪威] 玛格尼尔·文斯纳斯 绘 ', 'https://img2.doubanio.com/view/subject/s/public/s34559752.jpg', '2023-6', '精装', '9.6', 140);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (41, '二十世纪政治哲学', '[美]凯瑟琳·扎克特 编 ', 'https://img1.doubanio.com/view/subject/s/public/s34550957.jpg', '2023-6', '精装', '没有评分​', 12);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (42, '过劳死：这份工作比命还重要？', '[日] 牧内昇平 ', 'https://img9.doubanio.com/view/subject/s/public/s34538416.jpg', '2023-6', '平装', '8.4', 38);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (43, '美好事物的忧伤', '[英]西蒙·范·布伊 ', 'https://img2.doubanio.com/view/subject/s/public/s34538912.jpg', '2023-6', '精装', '7.2', 32);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (44, '阿尔戈', '[美国] 玛吉·尼尔森 ', 'https://img9.doubanio.com/view/subject/s/public/s34532506.jpg', '2023-6', '精装', '8.2', 172);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (45, '地虎噬天王：后金崛起的地理与自然环境综述', '秋原 ', 'https://img9.doubanio.com/view/subject/s/public/s34575235.jpg', '2023-6', '平装', '9.2', 130);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (46, '彼得·潘诺顿注释本', '[英] 詹姆斯·巴里 / [美] 玛丽亚·塔塔尔 编著 ', 'https://img9.doubanio.com/view/subject/s/public/s34507794.jpg', '2023-7', '精装', '没有评分​', 14);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (47, '然后，活下去', '坂元裕二 ', 'https://img2.doubanio.com/view/subject/s/public/s34498783.jpg', '2023-6', '平装', '7.8', 120);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (48, '美妆帝国蝴蝶牌：一部近代中国民间工业史', '[美]林郁沁 ', 'https://img2.doubanio.com/view/subject/s/public/s34550893.jpg', '2023-6', '精装', '9.1', 158);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (49, '拜访死者的旅行：尤内斯库戏剧全集5', '[法] 欧仁·尤内斯库 ', 'https://img2.doubanio.com/view/subject/s/public/s34557712.jpg', '2023-7', '精装', '没有评分​', 0);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (50, '异服新穿：近代中日服饰交流史', '刘玲芳 ', 'https://img9.doubanio.com/view/subject/s/public/s34558096.jpg', '2023-6', '精装', '没有评分​', 0);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (51, '历史学家的修养和技艺：修订本', '李剑鸣 ', 'https://img9.doubanio.com/view/subject/s/public/s34578125.jpg', '2023-6', '精装', '没有评分​', 2);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (52, '行动如何可能：鲁迅文学的一个思想脉络', '李国华 ', 'https://img2.doubanio.com/view/subject/s/public/s34521373.jpg', '2023-6', '精装', '没有评分​', 8);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (53, '最后的言者：为了保罗·策兰', '[法国] 雅克·德里达 / [法] 莫里斯·布朗肖 / [法国] 列维纳斯 / [美国] 乔治·斯坦纳 / 菲利普·拉库-拉巴特 / 埃莱娜·西苏 / [以色列] 耶胡达·阿米亥 / [法国] 伊夫·博纳富瓦 / [法国] E·M·齐奥朗 / 埃德蒙·雅贝斯 / 亨利·米肖 / 菲利普·雅戈泰 / 等 ', 'https://img9.doubanio.com/view/subject/s/public/s34547245.jpg', '2023-6', '平装', '9.2', 49);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (54, '永远的女儿', '[新西兰]琳达·科林斯 ', 'https://img1.doubanio.com/view/subject/s/public/s34527298.jpg', '2023-6', '平装', '8.2', 44);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (55, '门：1995-2007诗选', '[加] 玛格丽特·阿特伍德 ', 'https://img9.doubanio.com/view/subject/s/public/s34556904.jpg', '2023-7', '精装', '没有评分​', 9);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (56, '瓦斯灯', '[日] 连城三纪彦 ', 'https://img2.doubanio.com/view/subject/s/public/s34557871.jpg', '2023-6', '平装', '7.4', 241);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (57, '谁的问题：现代社会的非标准答案', '孟庆延 ', 'https://img1.doubanio.com/view/subject/s/public/s34558560.jpg', '2023-6', '69', '7.3', 61);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (58, '博尔赫斯教授：二十五堂文学课', '[阿根廷] 豪尔赫·路易斯·博尔赫斯 / [阿根廷] 马蒂恩·阿里亚斯 编 / [阿根廷] 马蒂恩 ·哈迪斯 编 ', 'https://img1.doubanio.com/view/subject/s/public/s34550548.jpg', '2023-7', '精装', '没有评分​', 6);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (59, '文化与国家', '[日] 南原繁 ', 'https://img9.doubanio.com/view/subject/s/public/s34545684.jpg', '2023-7', '精装', '没有评分​', 4);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (60, '还有谁谁谁', '黄永玉 ', 'https://img1.doubanio.com/view/subject/s/public/s34584479.jpg', '2023-7', '平装', '没有评分​', 18);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (61, '万物皆可测量：1250—1600年的西方', '[美]艾尔弗雷德·W. 克罗斯比 ', 'https://img1.doubanio.com/view/subject/s/public/s34551299.jpg', '2023-7', '精装', '9.0', 18);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (62, '理论入门：文学与文化理论导论', '[英] 彼得·巴里 ', 'https://img9.doubanio.com/view/subject/s/public/s34558945.jpg', '2023-6', '平装', '8.6', 35);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (63, '浮云', '[日] 林芙美子 ', 'https://img1.doubanio.com/view/subject/s/public/s34520139.jpg', '2023-6', '平装', '9.1', 65);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (64, '终场哨', '东平王千户 ', 'https://img9.doubanio.com/view/subject/s/public/s34519365.jpg', '2023-6', '平装', '8.0', 348);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (65, '欢迎来到物理学的世界', '[英] 吉姆·勒阿尔-哈利利 ', 'https://img9.doubanio.com/view/subject/s/public/s34535474.jpg', '2023-6', '平装', '8.6', 42);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (66, '美丽、遥远又野性', '[德] 马蒂亚斯·波利蒂基 ', 'https://img1.doubanio.com/view/subject/s/public/s34569367.jpg', '2023-7', '精装', '8.6', 15);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (67, '玛雅史：失落的世界第五大文明', '[美]罗伯特·J.沙雷尔 / [美]洛·P.特拉克斯勒 ', 'https://img2.doubanio.com/view/subject/s/public/s34562223.jpg', '2023-7', '精装', '没有评分​', 17);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (68, '深潜游戏Ⅰ：迷宫', '[俄罗斯] 谢尔盖·卢基扬年科 ', 'https://img1.doubanio.com/view/subject/s/public/s34550559.jpg', '2023-6', '平装', '8.6', 40);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (69, '后电影视觉：运动影像媒介与观众的共同进化', '（美）罗杰·F.库克 ', 'https://img9.doubanio.com/view/subject/s/public/s34562736.jpg', '2023-6', '精装', '9.1', 34);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (70, '当总统撒谎：官方欺骗及其后果的历史', '[美]埃里克·阿尔特曼 (Eric Alterman) ', 'https://img1.doubanio.com/view/subject/s/public/s34516830.jpg', '2023-6', '精装', '没有评分​', 9);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (71, '这就是ChatGPT', '[美] 斯蒂芬·沃尔弗拉姆（Stephen Wolfram） ', 'https://img1.doubanio.com/view/subject/s/public/s34566250.jpg', '2023-7', '平装', '8.6', 16);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (72, '春秋车战', '赵长征 ', 'https://img9.doubanio.com/view/subject/s/public/s34530404.jpg', '2023-6', '平装', '8.4', 69);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (73, '答案在风中飘：现代歌曲的哲学', '[美]鲍勃·迪伦著 ', 'https://img9.doubanio.com/view/subject/s/public/s34575236.jpg', '2023-6', '精装', '9.4', 39);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (74, '托尔金：中洲缔造者', '[英] 凯瑟琳·麦基尔韦恩 ', 'https://img9.doubanio.com/view/subject/s/public/s34394866.jpg', '2023-6', '精装', '9.6', 57);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (75, '幻象', '[美] 丹尼尔·布尔斯廷 ', 'https://img1.doubanio.com/view/subject/s/public/s34574290.jpg', '2023-7', '精装', '没有评分​', 9);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (76, '认知操纵：宣传如何影响我们的思想和行为（修订版）', '[美] 安东尼·普拉卡尼斯 / [美] 埃利奥特·阿伦森 ', 'https://img2.doubanio.com/view/subject/s/public/s34530492.jpg', '2023-6', '平装', '7.1', 39);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (77, '奇迹之书', '[爱尔兰]邓萨尼勋爵 ', 'https://img9.doubanio.com/view/subject/s/public/s34543374.jpg', '2023-6', '精装', '9.2', 43);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (78, '虚境奇谭：C.A.史密斯克苏鲁神话佳作集', '[美] C.A.史密斯 ', 'https://img2.doubanio.com/view/subject/s/public/s34382891.jpg', '2023-7', '精装', '7.7', 48);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (79, '成本与选择', '[美]詹姆斯·M. 布坎南 ', 'https://img9.doubanio.com/view/subject/s/public/s34522384.jpg', '2023-6', '精装', '没有评分​', 5);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (80, '履单：无所不有与一无所有', '[美] 亚历克·麦吉利斯 ', 'https://img9.doubanio.com/view/subject/s/public/s34542534.jpg', '2023-6', '平装', '8.4', 86);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (81, '撒马尔罕的荣光：阿夫拉西阿卜壁画解谜', '[意] 康马泰 ', 'https://img1.doubanio.com/view/subject/s/public/s34557760.jpg', '2023-6', '精装', '9.0', 23);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (82, '无人逝去', '[日] 白井智之 ', 'https://img9.doubanio.com/view/subject/s/public/s34565616.jpg', '2023-7', '平装', '8.0', 283);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (83, '深时之美：从宇宙星尘到人类文明，跨越45亿年的地球故事', '[美] 赖利·布莱克 ', 'https://img9.doubanio.com/view/subject/s/public/s34508126.jpg', '2023-6', '精装', '9.0', 39);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (84, '列夫·托尔斯泰：逃离乐园', '[俄罗斯]帕维尔·巴辛斯基 ', 'https://img9.doubanio.com/view/subject/s/public/s34524376.jpg', '2023-7', '精装', '没有评分​', 12);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (85, '停止自我破坏：摆脱内耗，6步打造高效行动力', '朱迪·霍（Judy Ho） ', 'https://img9.doubanio.com/view/subject/s/public/s34568226.jpg', '2023-6', '平装', '7.9', 23);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (86, '如何理解老婆的脑回路', '[日] 黑川伊保子 ', 'https://img1.doubanio.com/view/subject/s/public/s34530660.jpg', '2023-6', '平装', '8.0', 86);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (87, '大城市的兴衰：人类文明的乌托邦与反乌托邦', '[英]本·威尔逊 (Ben Wilson) ', 'https://img1.doubanio.com/view/subject/s/public/s34528350.jpg', '2023-6', '精装', '8.8', 19);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (88, '疫病年代：东汉至魏晋时期的瘟疫、战争与社会', '袁灿兴 ', 'https://img1.doubanio.com/view/subject/s/public/s34550078.jpg', '2023-8', '精装', '没有评分​', 8);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (89, '明代妇女生活', '陈宝良 ', 'https://img2.doubanio.com/view/subject/s/public/s34581881.jpg', '2023-6', '平装', '9.1', 20);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (90, '楚国兴亡史：华夏文明的开拓与融合', '张宏杰 ', 'https://img1.doubanio.com/view/subject/s/public/s34550158.jpg', '2023-6', '精装', '7.9', 143);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (91, '海上古籍风云录', '柳向春 ', 'https://img2.doubanio.com/view/subject/s/public/s34538533.jpg', '2023-6', '精装', '没有评分​', 4);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (92, '单身女性', '[日] 雨宫处凛 ', 'https://img2.doubanio.com/view/subject/s/public/s34538413.jpg', '2023-6', '平装', '7.8', 35);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (93, '嘉靖：一个帝王为何会厌惧皇宫', '卜键 ', 'https://img9.doubanio.com/view/subject/s/public/s34589984.jpg', '2023-6', '精装', '8.9', 49);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (94, '万国之子：布鲁岛四部曲2', '[印尼]普拉姆迪亚·阿南达·杜尔 ', 'https://img1.doubanio.com/view/subject/s/public/s34568229.jpg', '2023-7', '精装', '没有评分​', 8);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (95, '中国前近代的出版、文化与权力：16—17世纪', '(美) 周启荣 ', 'https://img9.doubanio.com/view/subject/s/public/s34531134.jpg', '2023-6', '平装', '8.5', 24);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (96, '虫与歌', '[日] 市川春子 ', 'https://img9.doubanio.com/view/subject/s/public/s34538444.jpg', '2023-6', '平装', '8.6', 102);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (97, '存在主义物理学', '[德]扎比内·霍森菲尔德 ', 'https://img1.doubanio.com/view/subject/s/public/s34556477.jpg', '2023-6', '精装', '没有评分​', 14);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (98, '理性：理性是什么，为什么如此稀缺，为什么如此重要？', '[美] 史蒂芬·平克（Steven Pinker） ', 'https://img1.doubanio.com/view/subject/s/public/s34549990.jpg', '2023-6', '精装', '8.4', 12);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (99, '蒙曼女性诗词课 邦媛', '蒙曼 ', 'https://img1.doubanio.com/view/subject/s/public/s34545020.jpg', '2023-6', '平装', '8.9', 50);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (100, '像这样的小事', '[爱尔兰]克莱尔·吉根 ', 'https://img9.doubanio.com/view/subject/s/public/s34516994.jpg', '2023-6', '精装', '8.0', 40);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (101, '沉思的生活，或无所事事', '[德]韩炳哲 ', 'https://img9.doubanio.com/view/subject/s/public/s34567165.jpg', '2023-7', '精装', '没有评分​', 5);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (102, '大松鸡', '[法] 米歇尔·图尼埃 ', 'https://img2.doubanio.com/view/subject/s/public/s34528361.jpg', '2023-6', '精装', '8.3', 48);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (103, '图书馆疗愈手记', '[英] 艾莉·摩根 / Allie Morgan ', 'https://img2.doubanio.com/view/subject/s/public/s34565123.jpg', '2023-7', '平装', '9.2', 44);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (104, '生存：加拿大文学主题指南', '[加] 玛格丽特·阿特伍德 ', 'https://img9.doubanio.com/view/subject/s/public/s34556915.jpg', '2023-7', '精装', '没有评分​', 8);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (105, '冲向火星：马斯克和 SpaceX 的初创故事', '[美] 艾瑞克·伯格 ', 'https://img9.doubanio.com/view/subject/s/public/s34552404.jpg', '2023-6', '平装', '8.5', 40);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (106, '夏洛克行动', '[美] 菲利普·罗斯 ', 'https://img2.doubanio.com/view/subject/s/public/s34550922.jpg', '2023-6', '精装', '没有评分​', 4);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (107, '自然而美：新艺术装饰设计图录', '莫里斯·皮亚尔-韦纳伊 ', 'https://img1.doubanio.com/view/subject/s/public/s34528088.jpg', '2023-6', '精装', '9.0', 78);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (108, '汉代的谣言：修订版', '吕宗力 ', 'https://img1.doubanio.com/view/subject/s/public/s34517128.jpg', '2023-6', '精装', '8.3', 34);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (109, '意识形态的起源：16世纪法国的意识与社会', '[英]唐纳德·克雷 ', 'https://img9.doubanio.com/view/subject/s/public/s34520855.jpg', '2023-6', '88', '8.6', 18);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (110, '门：一位女作家的自白', '[匈牙利] 萨博·玛格达 ', 'https://img9.doubanio.com/view/subject/s/public/s34525054.jpg', '2023-6', '平装', '8.8', 46);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (111, '在黄昏起飞', '[英]海伦·麦克唐纳（Helen Macdonald） ', 'https://img9.doubanio.com/view/subject/s/public/s34550925.jpg', '2023-6', '精装', '8.8', 19);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (112, '大卫·鲍伊访谈录', '[英]肖恩·伊根，编 ', 'https://img2.doubanio.com/view/subject/s/public/s34551513.jpg', '2023-6', '精装', '没有评分​', 14);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (113, '感受亲密：在关系中获得幸福的艺术', '曾旻 ', 'https://img9.doubanio.com/view/subject/s/public/s34526716.jpg', '2023-6', '平装', '8.5', 48);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (114, '困惑', '[美] 理查德·鲍尔斯 ', 'https://img2.doubanio.com/view/subject/s/public/s34536732.jpg', '2023-6', '平装', '8.7', 30);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (115, '学会写作 2.0', '粥左罗 ', 'https://img9.doubanio.com/view/subject/s/public/s34510754.jpg', '2023-6', '平装', '7.6', 53);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (116, '快乐的死', '[法] 阿尔贝·加缪 ', 'https://img1.doubanio.com/view/subject/s/public/s34579628.jpg', '2023-6', '平装', '8.3', 17);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (117, '冬牧场', '李娟 ', 'https://img9.doubanio.com/view/subject/s/public/s34570336.jpg', '2023-6', '平装', '没有评分​', 4);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (118, '不道德教育讲座', '[日]三岛由纪夫 ', 'https://img1.doubanio.com/view/subject/s/public/s34562859.jpg', '2023-6', '平装', '没有评分​', 5);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (119, '帝国与革命（上下）：埃德蒙·伯克的政治生涯', '[英]理查德·伯克 (Richard Bourke) ', 'https://img9.doubanio.com/view/subject/s/public/s34579204.jpg', '2023-7', '00', '没有评分​', 2);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (120, '普雷维尔不是诗人', '[法] 埃尔韦·布里 编 / [法] 克里斯蒂安·卡约 绘 ', 'https://img1.doubanio.com/view/subject/s/public/s34559688.jpg', '2023-6', '精装', '没有评分​', 10);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (121, '离世猫的花园', '[土] 比尔盖·卡拉素 ', 'https://img2.doubanio.com/view/subject/s/public/s34586161.jpg', '2023-6', '双色', '9.1', 24);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (122, '烽火世界：漫长的战争：1914—1945', '[英]丹·琼斯（Dan Jones） / [巴西]玛丽娜·阿马拉尔（Marina Amaral） / [英]马克·霍金斯-达迪（Mark Hawkins-Dady） ', 'https://img9.doubanio.com/view/subject/s/public/s34584265.jpg', '2023-6', '精装', '8.9', 20);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (123, '脆弱的国度：叙利亚500年', '[加]詹姆斯·A.赖利 ', 'https://img2.doubanio.com/view/subject/s/public/s34568552.jpg', '2023-7', '精装', '没有评分​', 1);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (124, '我的身体里住不下13个人：分离性身份识别障碍人士的非日常的日常', '[日] 晴 ', 'https://img9.doubanio.com/view/subject/s/public/s34535744.jpg', '2023-6', '平装', '8.7', 11);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (125, '如何写好学术论文', '[美] 詹姆斯·D.莱斯特 / 小詹姆斯·D.莱斯特 ', 'https://img1.doubanio.com/view/subject/s/public/s34510748.jpg', '2023-6', '平装', '没有评分​', 11);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (126, '水中舞者', '(美) 塔那西斯·科茨 (Ta-Nehisi Coates) ', 'https://img2.doubanio.com/view/subject/s/public/s34549712.jpg', '2023-7', '精装', '没有评分​', 18);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (127, '巴米扬大佛之劫：“9•11”的前奏', '[日] 高木彻 ', 'https://img1.doubanio.com/view/subject/s/public/s34539380.jpg', '2023-6', '平装', '8.8', 25);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (128, '金宫案', '曹操 ', 'https://img9.doubanio.com/view/subject/s/public/s34550035.jpg', '2023-7', '平装', '8.2', 37);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (129, '莎士比亚的科学：一位剧作家和他的时代', '[加]丹·福克 ', 'https://img1.doubanio.com/view/subject/s/public/s34568360.jpg', '2023-6', '平装', '没有评分​', 2);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (130, '欺凌自杀：12个孩子的父母的证言', '[日] 镰田慧 ', 'https://img1.doubanio.com/view/subject/s/public/s34539378.jpg', '2023-6', '平装', '8.5', 15);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (131, '熊廷弼之死：晚明政局的囚徒困境', '唐元鹏 ', 'https://img9.doubanio.com/view/subject/s/public/s34547975.jpg', '2023-6', '精装', '7.9', 243);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (132, '竹内好的悖论：（增订本）', '孙歌 ', 'https://img9.doubanio.com/view/subject/s/public/s34546234.jpg', '2023-6', '精装', '没有评分​', 13);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (133, '革命的身体：重新认识当代中国舞蹈文化', '[美]魏美玲 ', 'https://img1.doubanio.com/view/subject/s/public/s34558079.jpg', '2023-6', '精装', '没有评分​', 8);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (134, '在其他的世界：科幻小说与人类想象', '[加] 玛格丽特·阿特伍德 ', 'https://img1.doubanio.com/view/subject/s/public/s34544119.jpg', '2023-7', '精装', '没有评分​', 5);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (135, '不知归处：茨威格的流亡人生', '[美] 乔治·普罗尼克 ', 'https://img1.doubanio.com/view/subject/s/public/s34475137.jpg', '2023-6', '精装', '8.0', 29);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (136, '猫眼', '[法] 墨比斯 绘 / [法] 亚历桑德罗·佐杜洛夫斯基 编 ', 'https://img2.doubanio.com/view/subject/s/public/s34543341.jpg', '2023-6', '精装', '8.5', 106);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (137, '什么是权力？', '[德]韩炳哲 ', 'https://img9.doubanio.com/view/subject/s/public/s34567164.jpg', '2023-7', '精装', '没有评分​', 3);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (138, '1494：瓜分世界的条约与大航海时代的来临', '[加] 斯蒂芬·R. 鲍恩 ', 'https://img1.doubanio.com/view/subject/s/public/s34547290.jpg', '2023-6', '精装', '没有评分​', 3);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (139, '平成时代', '[日] 吉见俊哉 ', 'https://img1.doubanio.com/view/subject/s/public/s34545630.jpg', '2023-6', '平装', '7.8', 156);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (140, '新美术海：日本明治时代纹样艺术', '[日] 古谷红麟  / 神坂雪佳 ', 'https://img2.doubanio.com/view/subject/s/public/s34559143.jpg', '2023-7', '精装', '没有评分​', 7);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (141, '一个地图上找不到的地方', '岱峻 ', 'https://img1.doubanio.com/view/subject/s/public/s34550180.jpg', '2023-6', '精装', '没有评分​', 10);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (142, '最后的演讲', '[美]兰迪·波许 / [美]杰弗里·扎斯洛 ', 'https://img1.doubanio.com/view/subject/s/public/s34558408.jpg', '2023-7', '精装', '没有评分​', 3);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (143, '小镇索雷斯', '[加] 玛丽·劳森 ', 'https://img1.doubanio.com/view/subject/s/public/s34500719.jpg', '2023-6', '平装', '8.0', 77);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (144, '高敏感：被低估的品质与天赋', '(法) 法布里斯·米达勒 ', 'https://img9.doubanio.com/view/subject/s/public/s34552444.jpg', '2023-6', '平装', '6.0', 56);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (145, '心智与政治秩序', '吴彦 ', 'https://img1.doubanio.com/view/subject/s/public/s34588589.jpg', '2023-6', '平装', '没有评分​', 4);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (146, '钻石广场', '[西] 梅尔赛·罗多雷达 ', 'https://img9.doubanio.com/view/subject/s/public/s34490275.jpg', '2023-6', '平装', '8.3', 240);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (147, '英语科技写作：第二版', '[英]希拉里·格拉斯曼-蒂欧 (Hilary Glasman‐Deal) ', 'https://img1.doubanio.com/view/subject/s/public/s34556847.jpg', '2023-6', '平装', '没有评分​', 4);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (148, '我要它们活下去：熊本市流浪动物零扑杀十年奋斗纪实', '[日]片野由佳 ', 'https://img2.doubanio.com/view/subject/s/public/s34500893.jpg', '2023-6', '平装', '8.7', 22);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (149, '非亲非故', '索耳 ', 'https://img2.doubanio.com/view/subject/s/public/s34568491.jpg', '2023-6', '平装', '9.2', 28);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (150, '萨满教与神话', '富育光 ', 'https://img9.doubanio.com/view/subject/s/public/s34562115.jpg', '2023-6', '平装', '没有评分​', 3);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (151, '太冷、太热、太早、太迟：美好生活的什锦拼盘', '[比] 托马斯·冈兹格 ', 'https://img2.doubanio.com/view/subject/s/public/s34560983.jpg', '2023-6', '平装', '7.6', 72);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (152, '创伤的帝国', '[法]迪迪埃·法桑 / [法]理查德·李森特曼 ', 'https://img2.doubanio.com/view/subject/s/public/s34586122.jpg', '2023-6', '精装', '没有评分​', 1);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (153, '从元宇宙到量子现实：迈向后人类主义政治本体论', '吴冠军 ', 'https://img1.doubanio.com/view/subject/s/public/s34558080.jpg', '2023-6', '精装', '9.3', 30);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (154, '历史写作的新视野', '[英]彼得·伯克 主编 ', 'https://img2.doubanio.com/view/subject/s/public/s34584493.jpg', '2023-6', '平装', '没有评分​', 6);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (155, '必须写下我们：被写作改变的人生', '吴越 ', 'https://img9.doubanio.com/view/subject/s/public/s34532504.jpg', '2023-6', '平装', '9.6', 22);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (156, '焚书：知识的受难史', '[英] 理查德·奥文登 ', 'https://img9.doubanio.com/view/subject/s/public/s34565124.jpg', '2023-7', '精装', '没有评分​', 12);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (157, '前四史解读', '王保顶 ', 'https://img9.doubanio.com/view/subject/s/public/s34558526.jpg', '2023-6', '精装', '9.5', 20);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (158, '先发制人：摩萨德、辛贝特、IDF定点清除行动秘史', '[以] 罗南·伯格曼 ', 'https://img1.doubanio.com/view/subject/s/public/s34517618.jpg', '2023-6', '平装', '7.5', 17);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (159, '山中', '张定浩 ', 'https://img1.doubanio.com/view/subject/s/public/s34560597.jpg', '2023-6', '平装', '8.3', 58);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (160, '不大可能', '[法]伊夫·博纳富瓦 ', 'https://img9.doubanio.com/view/subject/s/public/s34589945.jpg', '2023-7', '精装', '没有评分​', 2);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (161, '野史记：近代中国异闻录', '杨早 ', 'https://img2.doubanio.com/view/subject/s/public/s34521492.jpg', '2023-6', '精装', '没有评分​', 13);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (162, '西方现代思想史：从中世纪到启蒙运动', '[美]罗兰·斯特龙伯格 ', 'https://img2.doubanio.com/view/subject/s/public/s34571222.jpg', '2023-7', '精装', '没有评分​', 4);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (163, '人种：西方人种概念的建构、传布与解构', '孙江 ', 'https://img2.doubanio.com/view/subject/s/public/s34559112.jpg', '2023-6', '精装', '8.5', 25);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (164, '奥斯维辛：寂静的城市', '[意]普里莫·莱维 / [意]法比奥·莱维 编 / [意]多梅尼科·斯卡帕 编 ', 'https://img2.doubanio.com/view/subject/s/public/s34585001.jpg', '2023-7', '平装', '没有评分​', 3);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (165, '漫长岁月，没有一天是适合上班的', '动物办公室 ', 'https://img1.doubanio.com/view/subject/s/public/s34587620.jpg', '2023-7', '平装', '没有评分​', 21);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (166, '如何理解老公的脑回路', '[日] 黑川伊保子 ', 'https://img2.doubanio.com/view/subject/s/public/s34530662.jpg', '2023-6', '平装', '7.2', 103);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (167, '经济学好实用：如果没有被误读的话', '(土) 丹尼·罗德里克 (Dani Rodrik) ', 'https://img2.doubanio.com/view/subject/s/public/s34559391.jpg', '2023-6', '平装', '没有评分​', 8);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (168, '中国建筑史：（通校本）', '梁思成 ', 'https://img1.doubanio.com/view/subject/s/public/s34524518.jpg', '2023-6', '精装', '8.6', 13);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (169, '风沙星辰', '[法]安托万·德·圣埃克苏佩里 ', 'https://img9.doubanio.com/view/subject/s/public/s34561986.jpg', '2023-6', '精装', '9.3', 43);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (170, '极端主义', 'J. M. 伯杰 ', 'https://img9.doubanio.com/view/subject/s/public/s34540066.jpg', '2023-7', '平装', '没有评分​', 15);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (171, '博物馆是什么', '陈建明 / 张小溪 ', 'https://img2.doubanio.com/view/subject/s/public/s34524512.jpg', '2023-6', '精装', '8.5', 18);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (172, '他者的起源', '[美] 托妮·莫里森 ', 'https://img1.doubanio.com/view/subject/s/public/s34556939.jpg', '2023-7', '精装', '没有评分​', 8);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (173, '东京往事', '[日]松原岩五郎 ', 'https://img2.doubanio.com/view/subject/s/public/s34544093.jpg', '2023-7', '平装', '没有评分​', 1);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (174, '乱世人心：从晚唐到五代', '王宏杰 ', 'https://img9.doubanio.com/view/subject/s/public/s34557775.jpg', '2023-7', '精装', '没有评分​', 9);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (175, '不安的智慧：焦虑年代的启示', '[美] 阿伦·瓦兹 ', 'https://img2.doubanio.com/view/subject/s/public/s34530612.jpg', '2023-6', '平装', '9.2', 18);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (176, '未作回答的问题：伯恩斯坦哈佛六讲', '[美]伦纳德·伯恩斯坦 ', 'https://img9.doubanio.com/view/subject/s/public/s34579704.jpg', '2023-7', '平装', '没有评分​', 8);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (177, '郁金香花开的雨夜', '[美] 戴维·伽特森 ', 'https://img2.doubanio.com/view/subject/s/public/s34544773.jpg', '2023-7', '平装', '没有评分​', 14);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (178, '贫民窟：全球不公的历史', '[英] 艾伦·梅恩 ', 'https://img2.doubanio.com/view/subject/s/public/s34571763.jpg', '2023-7', '平装', '没有评分​', 2);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (179, '从封建到大一统：《史记》中的历史中国', '韩昇 ', 'https://img2.doubanio.com/view/subject/s/public/s34526691.jpg', '2023-6', '精装', '7.8', 26);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (180, '吴宓的精神世界', '周轶群 ', 'https://img2.doubanio.com/view/subject/s/public/s34579202.jpg', '2023-6', '平装', '没有评分​', 3);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (181, '此处葬曹操', '唐际根 ', 'https://img1.doubanio.com/view/subject/s/public/s34579099.jpg', '2023-6', '平装', '8.1', 66);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (182, '宇宙创世记', '[意]圭多·托奈利 ', 'https://img9.doubanio.com/view/subject/s/public/s34562154.jpg', '2023-6', '平装', '没有评分​', 3);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (183, '宇宙的无限与虚无', '[美]艾伦·莱特曼 ', 'https://img2.doubanio.com/view/subject/s/public/s34563761.jpg', '2023-7', '精装', '8.3', 15);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (184, '印度国家博物馆', '梅辰 ', 'https://img1.doubanio.com/view/subject/s/public/s34572300.jpg', '2023-6', '平装', '没有评分​', 2);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (185, '炙热的你：关于了不起的女性更年期的一切', '[德]希拉•德利兹 / [德] 路易莎•施托默尔 ', 'https://img2.doubanio.com/view/subject/s/public/s34484633.jpg', '2023-6', '平装', '8.4', 177);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (186, '步步娇：单雯说剧谈情', '单雯 ', 'https://img2.doubanio.com/view/subject/s/public/s34574813.jpg', '2023-7', '平装', '8.8', 14);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (187, '反霸凌：家长、老师和孩子如何终结恐惧循环', '[美] 卡丽·戈德曼 ', 'https://img2.doubanio.com/view/subject/s/public/s34551123.jpg', '2023-7', '平装', '没有评分​', 1);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (188, '皮扎尼克传：最后的天真', '[阿根廷] 塞萨尔·艾拉 ', 'https://img1.doubanio.com/view/subject/s/public/s34538728.jpg', '2023-6', '精装', '8.4', 36);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (189, '一本战时风雅笺', '岱峻 ', 'https://img2.doubanio.com/view/subject/s/public/s34550181.jpg', '2023-6', '精装', '没有评分​', 8);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (190, '春秋时期齐、卫、晋、秦交通路线考论', '徐鼎鼎 ', 'https://img2.doubanio.com/view/subject/s/public/s34579361.jpg', '2023-7', '精装', '没有评分​', 1);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (191, '赫尔德的社会政治思想：在启蒙运动与政治浪漫主义之间', '[加]巴纳德 (Frederick M. Barnard) ', 'https://img1.doubanio.com/view/subject/s/public/s34559397.jpg', '2023-6', '平装', '没有评分​', 3);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (192, '写一百年再停笔：托纳多雷对谈莫里康内', '[意] 埃尼奥·莫里康内 / [意] 朱塞佩·托纳多雷 ', 'https://img1.doubanio.com/view/subject/s/public/s34577698.jpg', '2023-7', '精装', '没有评分​', 11);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (193, '植物的艺术', '[德]卡尔·布洛斯菲尔德/摄 / [德]汉斯约尔格·屈斯特/撰 ', 'https://img1.doubanio.com/view/subject/s/public/s34518890.jpg', '2023-7', '精装', '9.1', 17);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (194, '地质词典：Geopedia', '[美]马西娅·比约内鲁德（Marcia Bjornerud） 著 / [美]黑利·哈格曼（Haley Hagerman） 绘 ', 'https://img1.doubanio.com/view/subject/s/public/s34567228.jpg', '2023-6', '精装', '没有评分​', 9);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (195, '爱尔娜', '[波兰] 奥尔加·托卡尔丘克 ', 'https://img9.doubanio.com/view/subject/s/public/s34545686.jpg', '2023-6', '平装', '6.9', 33);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (196, '美术、神话与祭祀', '张光直 ', 'https://img2.doubanio.com/view/subject/s/public/s34413722.jpg', '2023-6', '精装', '9.3', 21);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (197, '岛上寻星', '[美] 艾伦·莱特曼 ', 'https://img2.doubanio.com/view/subject/s/public/s34563733.jpg', '2023-7', '精装', '没有评分​', 11);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (198, '世界战争史', '[英] 杰里米·布莱克 / [美] 史蒂芬 ·莫里略 / [美] 保罗·洛科科 ', 'https://img9.doubanio.com/view/subject/s/public/s34565916.jpg', '2023-6', '精装', '没有评分​', 4);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (199, '中国人的茶事', '戴明华 ', 'https://img1.doubanio.com/view/subject/s/public/s34563038.jpg', '2023-7', '精装', '没有评分​', 3);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (200, '马克思主义与世界政治：争论中的全球资本主义', '[美]亚历山大·阿涅瓦斯（Alexander Anievas） 编 ', 'https://img9.doubanio.com/view/subject/s/public/s34588585.jpg', '2023-6', '平装', '没有评分​', 1);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (201, '如果你生在罗马帝国', '薄海昆 ', 'https://img2.doubanio.com/view/subject/s/public/s34552861.jpg', '2023-6', '平装', '8.4', 14);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (202, '近代中国大众教育的兴起：1927—1937', '冯淼 ', 'https://img2.doubanio.com/view/subject/s/public/s34552322.jpg', '2023-6', '版社', '没有评分​', 2);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (203, '社会科学的未来', '[美]安德鲁·阿伯特 ', 'https://img9.doubanio.com/view/subject/s/public/s34577474.jpg', '2023-6', '平装', '没有评分​', 4);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (204, '李白传', '李长之 ', 'https://img1.doubanio.com/view/subject/s/public/s34586160.jpg', '2023-7', '精装', '没有评分​', 4);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (205, '国王正在死去：尤内斯库戏剧全集4', '[法] 欧仁·尤内斯库 ', 'https://img1.doubanio.com/view/subject/s/public/s34545810.jpg', '2023-6', '精装', '没有评分​', 3);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (206, '仪式', '[美] 莱斯利·马蒙·西尔科 ', 'https://img9.doubanio.com/view/subject/s/public/s34544505.jpg', '2023-6', '平装', '没有评分​', 10);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (207, '不在场：东亚文化与哲学', '[德]韩炳哲 ', 'https://img1.doubanio.com/view/subject/s/public/s34565600.jpg', '2023-7', '精装', '没有评分​', 3);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (208, '让-雅克·卢梭与亚当·斯密：一场哲学的相遇', '[美] 查尔斯·L.格瑞斯沃德 ', 'https://img9.doubanio.com/view/subject/s/public/s34545984.jpg', '2023-7', '平装', '没有评分​', 5);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (209, '今天的天气适合离职', '秀珍与二狸 ', 'https://img1.doubanio.com/view/subject/s/public/s34550130.jpg', '2023-6', '平装', '7.2', 231);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (210, '战时日本的媒体组合：《翼赞一家》与社会动员', '[日] 大塚英志 ', 'https://img2.doubanio.com/view/subject/s/public/s34571762.jpg', '2023-8', '平装', '没有评分​', 0);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (211, '虽然我的头发这么乱', '[日] 吉竹伸介 ', 'https://img1.doubanio.com/view/subject/s/public/s34587617.jpg', '2023-6', '精装', '9.2', 114);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (212, '春天里的同学会', '常潇湘 / 孙铎 ', 'https://img1.doubanio.com/view/subject/s/public/s34583297.jpg', '2023-6', '精装', '8.6', 49);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (213, '西高地行记', '阿来 ', 'https://img2.doubanio.com/view/subject/s/public/s34556863.jpg', '2023-6', '精装', '9.1', 24);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (214, '川端康成经典名作集', '[日]川端康成 ', 'https://img2.doubanio.com/view/subject/s/public/s34588583.jpg', '2023-6', '精装', '9.5', 76);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (215, '浮现', '[加] 玛格丽特·阿特伍德 ', 'https://img1.doubanio.com/view/subject/s/public/s34556918.jpg', '2023-7', '精装', '没有评分​', 9);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (216, '伊朗艺术史', '[伊朗] 哈比比安拉·阿亚图拉希 ', 'https://img1.doubanio.com/view/subject/s/public/s34578848.jpg', '2023-6', '精装', '没有评分​', 1);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (217, '在细雨中呼喊', '余华 ', 'https://img2.doubanio.com/view/subject/s/public/s34569411.jpg', '2023-7', '精装', '9.4', 31);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (218, '夏日木屋札记：一场跨越物种的生命对话', '(瑞典) 妮娜·波顿 ', 'https://img1.doubanio.com/view/subject/s/public/s34570339.jpg', '2023-7', '精装', '没有评分​', 6);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (219, '刻意专注：分心时代如何找回高效的喜悦', '[美] 阿米希·P.杰哈 ', 'https://img2.doubanio.com/view/subject/s/public/s34569341.jpg', '2023-7', '平装', '没有评分​', 5);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (220, '奇想与微笑：太宰治短篇杰作选', '[日]太宰治 著 / [日]森见登美彦 编著 ', 'https://img9.doubanio.com/view/subject/s/public/s34527424.jpg', '2023-6', '精装', '8.0', 27);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (221, '菜菜子，恋爱吧', '[日] 黑孩 ', 'https://img2.doubanio.com/view/subject/s/public/s34562013.jpg', '2023-6', '平装', '9.6', 18);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (222, '深潜游戏Ⅱ：镜子', '[俄罗斯] 谢尔盖·卢基扬年科 ', 'https://img1.doubanio.com/view/subject/s/public/s34550560.jpg', '2023-6', '平装', '没有评分​', 12);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (223, '私人铸币：工业革命时代的货币世界1775—1821', '[美]乔治·塞尔金 ', 'https://img9.doubanio.com/view/subject/s/public/s34578836.jpg', '2023-7', '精装', '没有评分​', 0);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (224, '学术写作五步法：如何从零完成高质量论文', '王树义 ', 'https://img1.doubanio.com/view/subject/s/public/s34560589.jpg', '2023-8', '平装', '没有评分​', 5);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (225, '妖怪事典', '王新禧 ', 'https://img9.doubanio.com/view/subject/s/public/s34540034.jpg', '2023-6', '平装', '8.6', 39);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (226, '拒绝想象', '徐兆正 ', 'https://img2.doubanio.com/view/subject/s/public/s34545853.jpg', '2023-6', '精装', '没有评分​', 5);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (227, '语言迷宫', '[美]约翰·H.麦克沃特 ', 'https://img2.doubanio.com/view/subject/s/public/s34540142.jpg', '2023-6', '平装', '没有评分​', 2);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (228, '为进步定价：美国经济指标演变简史', '[美] 伊莱·库克 ', 'https://img1.doubanio.com/view/subject/s/public/s34581779.jpg', '2023-6', '平装', '没有评分​', 4);
INSERT INTO `db` (`id`, `name`, `author`, `picture`, `time`, `version`, `score`, `count_people`) VALUES (229, '有一天出事了：微小说集', '[西班牙]雷内·梅里诺（René Merino） ', 'https://img1.doubanio.com/view/subject/s/public/s34507687.jpg', '2023-6', '精装', '8.5', 55);
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
